# drawCurvesMaya2.py
#-----------------------------------------------------------
# Reads files written by queryParticles and generates
# curves that represent each particle's individual path
#-----------------------------------------------------------
# Chance Payne and Kyle Nikolich
# April 2009

import os
import linecache
import maya.mel as mel

# Creates curves based on array generated in readFiles
def drawMayaCurves(readPart):
	
	# Begin creating curve mel statement
	buildCurve = "curve -d 3 "
	
	# Add positions
	for n in range ( len(readPart) ):
		buildCurve += "-p %s " % readPart[n]
	buildCurve += ";\n"
	
	#print "Your curve has been generated, sire... \n"
	#print buildCurve
	
	# Execute the curve statement
	mel.eval(buildCurve)


# Creates an array of position information read from
# files generated by getPositions within queryParticles.py
def readFiles (partPath, pNum):

	#Set path based on particle number
	pPath = partPath + "/particleNum" + str(pNum) + ".mel"
	
	# Open file for reading based on path, read content
	filePart = open(pPath, 'r')
	fileLength = len(filePart.readlines())
	
	# Initialize counter for getLine command
	line = 0
	
	# Initialize array for storing point positions
	readPart = []
	
	# Cycle through individual particle files
	# Read each line to get position information
	for n in range(fileLength):
		
		line = n + 1
		readPart.append(linecache.getline(pPath, line))
		
		# Remove end of line character from entry
		if readPart[n][-1] == '\n':
			 readPart[n] = readPart[n][:-1]
		
		# Clear cache for future values
		linecache.clearcache()
	
	# Call on drawMayaCurves to generate curves, pass array
	drawMayaCurves(readPart)
	

# Main procedure called to read data and generate curves
def masterControl (path):
	
	pPath = ("%s/particles") % path
	
	# Returns number of files within a directory
	num = os.listdir(pPath)
	numFiles = len(num)	
	
	# Call to readFiles for each file in the directory
	for n in range(numFiles):
		readFiles(pPath, n)
		
# Call masterControl to get this party started	
#masterControl()

